export const teams = [
    'Rusia', 
    'Alemania',
    'Brasil',
    'Portugal',
    'Argentina',
    'Bélgica',
    'Polonia',
    'Francia',
    'España',
    'Perú',
    'Suiza',
    'Inglaterra',
    'Colombia',
    'Croacia',
    'México',
    'Uruguay',
    'Dinamarca',
    'Suecia',
    'Islandia',
    'Costa Rica',
    'Túnez',
    'Egipto',
    'Senegal',
    'Irán',
    'Serbia',
    'Nigeria',
    'Japón',
    'Marruecos',
    'Panamá',
    'Corea del Sur',
    'Arabia Saudí',
    'Australia',
]

